### PR TITLE
Fixed ScioSense_ENS160.cpp: not only esp32 support others i2c bus + README

### PR DESCRIPTION
**Pull request by lollo03**
Esp8266 can change the i2c bus pins too.

Tested on an adafruit D1 mini

### CODE REVIEW

**Comment by lollo03** [comment]
I also added some documentation for the setI2C() function. @ladyada can you review this?

**Comment by ladyada** [comment]
we will not merge. use setPins() instead
https://github.com/espressif/arduino-esp32/issues/3779

**Comment by lollo03** [comment]
@ladyada so you basically want me to change the function name from setI2C() to setPins(). Correct?

**Comment by ladyada** [comment]
nono, you should call setPins on Wire()

**Comment by lollo03** [comment]
> nono, you should call setPins on Wire()

I'll do that. It may be useful to delete to delete the setI2C() function and add something to the README.

**Comment by ladyada** [comment]
we probably will :)

**Pull request closed without merging**
